spring:
   application:
      name: gateway
   cloud:
      gateway:
        routes:
          - id: submission-microservice
            uri: lb://submission-microservice
            predicates:
              - Path=/api/v1/submissions/**

          - id: task-serv
            uri: lb://TASK-SERV
            predicates:
              - Path=/api/v1/tasks/**, /api/v1/tasks/assigned/**

          - id: user-microservice
            uri: lb://user-microservice
            predicates:
              - Path=/user-microservice/**, /auth/**, /users/**, /api/v1/users/**, /api/v1/**, /

          #  - id: submission-microservice
          #    uri: lb://submission-microservice
          #    predicates:
          #      - Path=/api/v1/submissions/**, /api/v1/**, /submissions/**, /

        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"

   main:
    web-application-type: reactive

server:
  port: 5000
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


# https://youtu.be/6Ts4UdbIs-o?si=CV8yM9aXjZjYR0KE
